# Variable 'KeyAlias' was defined in the Variables tab
# Variable 'KeyPassword' was defined in the Variables tab
trigger:
  branches:
    include:
    - feature/my_changes
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: feature/my_changes
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Gradle@2
    displayName: gradlew build
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      publishJUnitResults: false
      tasks: assembleRelease
  - task: AndroidSigning@3
    displayName: Signing and aligning APK file(s) **/*.apk
    inputs:
      keystoreFile: 473b86d3-516a-4115-950c-7b0aea1462e0
      keystorePass: $(KeyPassword)
      keystoreAlias: $(KeyAlias)
      keyPass: $(KeyPassword)
      apkSignerArguments: '--verbose'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.apk'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publishing Build Artifacts'
    continueOnError: false
    inputs:
      pathToPublish: $(build.artifactstagingdirectory)
      artifactName: 'outputs'
      artifactType: 'container'

  - template: appcenter_deploy_template.yml
    parameters:
      listOfApks: [
          "$(build.artifactstagingdirectory)/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk",
          "$(build.artifactstagingdirectory)/app/build/outputs/apk/internal/release/app-internal-release-unsigned.apk",
          "$(build.artifactstagingdirectory)/app/build/outputs/apk/public/release/app-public-release-unsigned.apk"
      ]
...
